remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Boris Albar]
description:
<p align="center">
  <a href="">Resume</a> |
  <a href="https://www.linkedin.com/in/boris-albar/">LinkedIn</a> |
  <a href="https://github.com/b-albar">GitHub</a>
</p>
  
<p align="justify">
  I am a data scientist with a particular interest in applying deep learning to solve various problems,
  from computer vision and NLU to time series analysis. I'm currenly a lead data scientist at <a href="https://www.catie.fr/en/home/">CATIE</a>. I
  <br><br>
  In a previous life, I was interested in studying the structure of specific classes of  <a href="https://dblp.org/pid/137/5048.html">graphs and matroids</a>.
  <br><br>
  </p>

email: boris.albar@protonmail.com
show_downloads: "false"
