remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Boris Albar
description: <link href="description.html" rel="import" />

email: boris.albar@protonmail.com
show_downloads: "false"
